spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hbyy_map?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
server:
  port: 8082
# MyBatis配置
#mybatis:
#  # 搜索指定包别名
#  typeAliasesPackage: mymap.item.entity
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath:mapper/**/*Mapper.xml